# Site settings
title: Yichi Zhang
email: zhang-yi-chi@hotmail.com 
description: > # this means to ignore newlines until "baseurl:"
  I'm a computer programmer based in Melbourne, Australia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yichizhang.github.io" # the base hostname & protocol for your site
# twitter_username: 
github_username: yichizhang

# Build settings
markdown: kramdown
